name: cypress-end-to-end-tests
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
jobs:
  # This job is made to setup path filtering, learn more about it here: https://github.com/facebookresearch/Mephisto/pull/857
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filters step below
    outputs:
      simple_static_task: ${{ steps.filter.outputs.simple_static_task }}
      static_react_task: ${{ steps.filter.outputs.static_react_task }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      # Workaround to avoid Post Use step failures. See: https://github.com/actions/setup-node/issues/317
      - run: mkdir -p /home/runner/work/Mephisto/Mephisto/.yarn/cache
        continue-on-error: true
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 16
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            simple_static_task:
              - 'examples/simple_static_task/**'
            static_react_task:
              - 'examples/static_react_task/**'
            static_react_task_with_tips:
              - 'examples/static_react_task_with_tips/**'
            mnist:
              - 'examples/remote_procedure/mnist/**'
            template:
              - 'examples/remote_procedure/template/**'
            toxicity_detection:
              - 'examples/remote_procedure/toxicity_detection/**'
            abstractions:
              - 'mephisto/abstractions/**'
            data_model:
              - 'mephisto/data_model/**'
            operations:
              - 'mephisto/operations/**'
            tools:
              - 'mephisto/tools/**'
            mephisto-task:
              - 'packages/mephisto-task/src/**'
            mephisto-worker-addons:
              - 'packages/mephisto-worker-addons/src/**'

  # Learn more about this test here: https://github.com/facebookresearch/Mephisto/pull/881
  simple_static_task:
    needs: changes
    if: ${{ (needs.changes.outputs.simple_static_task == 'true') || (needs.changes.outputs.mephisto-task == 'true') || (needs.changes.outputs.abstractions == 'true') || (needs.changes.outputs.data_model == 'true') || (needs.changes.outputs.operations == 'true') || (needs.changes.outputs.tools == 'true')}}
    runs-on: ubuntu-latest
    steps:
      - name: 🔀 Checking out repo
        uses: actions/checkout@v2

      - name: 🐍 Installing python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 🪨 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: 🤖 Install Mephisto
        run: pip install -e .

      - name: 🖋 Create data directory
        run: mkdir -p ~/mephisto/data

      - name: 📂 Set the data directory
        run: mephisto config core.main_data_directory ~/mephisto/data

      - name: 📦 Setting up mephisto-task package
        run: |
          cd packages/mephisto-task
          yarn install
          yarn build
          npm link

      - name: ⌛️ Running cypress tests
        uses: cypress-io/github-action@v3.1.0
        with:
          build: npm i -D cypress@11
          install: false
          browser: chrome
          project: ./mephisto/abstractions/blueprints/static_html_task/source
          config-file: ./cypress.config.js
          start: python ./examples/simple_static_task/static_test_script.py
          wait-on: "http://localhost:3000/?worker_id=x&assignment_id=1"
          headless: true

  # Learn more about this test here: https://github.com/facebookresearch/Mephisto/pull/795
  static-react-task:
    needs: changes
    if: ${{ (needs.changes.outputs.static_react_task == 'true') || (needs.changes.outputs.mephisto-task == 'true') || (needs.changes.outputs.abstractions == 'true') || (needs.changes.outputs.data_model == 'true') || (needs.changes.outputs.operations == 'true') || (needs.changes.outputs.tools == 'true')}}
    runs-on: ubuntu-latest
    steps:
      - name: 🔀 Checking out repo
        uses: actions/checkout@v2

      - name: 🐍 Installing python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: 🪨 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: 🤖 Install Mephisto
        run: pip install -e .

      - name: 🖋 Create data directory
        run: mkdir -p ~/mephisto/data

      - name: 📂 Set the data directory
        run: mephisto config core.main_data_directory ~/mephisto/data

      - name: 📦 Setting up mephisto-task package
        run: |
          cd packages/mephisto-task
          yarn install
          yarn build
          npm link

      - name: ⌛️ Running cypress tests
        uses: cypress-io/github-action@v3.1.0
        with:
          build: npm i -D cypress@11
          install: false
          browser: chrome
          project: ./examples/static_react_task/webapp
          config-file: ./cypress.config.js
          start: python examples/static_react_task/run_task.py mephisto.task.post_install_script=link_mephisto_task.sh
          wait-on: "http://localhost:3000/?worker_id=x&assignment_id=1"
          headless: true

